package jclass.enums;

public enum CandleChartsEnum {
    DOWNWARD_TREND_ASC,
    DOWNWARD_TREND_COUNT_ASC,
    DOWNWARD_TREND_COUNT_DESC,
    DOWNWARD_TREND_DESC,

    UPWARD_TREND_ASC,
    UPWARD_TREND_DESC,
    UPWARD_TREND_COUNT_ASC,
    UPWARD_TREND_COUNT_DESC,
    UPWARD_TREND_NEAREST_SLOPE_SECOND_ORDER_SORT_DESC,
    RECENT_TWO_UPWARD_TREND_SECOND_ORDER_SORT_DESC,
    RECENT_TWO_DOWNWARD_TREND_SECOND_ORDER_SORT_DESC,
    DOWNWARD_TREND_NEAREST_SLOPE_SECOND_ORDER_SORT_ASC
}
